name: ebay-config

api.sandbox.ebay.com:
  appid: YanyangG-getitemf-SBX-3ac2147f3-d502e7c2
  certid: SBX-ac2147f3f866-0c48-4220-aa8f-e154
  devid: d46bb423-7fc7-4154-befb-74946615059e
  redirecturi: http://localhost

api.ebay.com:
  appid: YanyangG-getitemf-PRD-bac29f330-ac60a96b
  certid: PRD-ac29f3305a84-128b-4d94-bea9-eaff
  devid: d46bb423-7fc7-4154-befb-74946615059e
  redirecturi: http://localhost